### ISSUE TITLE
can't run

### ISSUE THREAD

**Issue by bubnenkoff** [huntlabs/hunt-skeleton#1]
latest build:

http://img.ctrlv.in/img/16/09/21/57e2829dde83b.png

**Comment by donglei** [comment]
give me your source code, fixed for you

**Comment by zoujiaqing** [comment]
I'm sorry!
Last night...
http default port is 8081, but the code is print 8080.

**Comment by bubnenkoff** [comment]
Ehm... http://img.ctrlv.in/img/16/09/22/57e3829bac493.png
8080 do not work too

**Comment by donglei** [comment]
We fixed it; Hunt can run in windows. you can clone this repos to your local, and run dub run command, enjoy it!
http://img.ctrlv.in/img/16/09/22/57e3aab991800.png

**Comment by donglei** [comment]
for more usage, you can find it in hunt example.

**Comment by bubnenkoff** [comment]
@donglei I still can't get it work :( After cloning and running `dub` I still get http://img.ctrlv.in/img/16/09/22/57e3b5c070658.png
and url lile: http://0.0.0.0:8080/ look strange

I tried to open http://127.0.0.1:8080/ and http://127.0.0.1:8081/ 

No success

**Comment by donglei** [comment]
what is your dub and dmd version ? and your windows version? I mail you an exe, try it. if not run, pls give me details  error  message

**Comment by bubnenkoff** [comment]
@donglei  I do not see any attaches...

**Comment by donglei** [comment]
@bubnenkoff resend mail for you
